const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");
const html = read("index.html");
const editorCss = read("styles/editor.css");
const componentCss = read("styles/components.css");
const renderer = read("app/renderer.js");
const interactions = read("app/interactions.js");
const assetLibrary = read("app/asset-library.js");
const assetStorage = read("app/asset-storage.js");
const productCatalog = read("app/product-catalog.js");
const inspector = read("app/inspector.js");
const workspaceLayout = read("app/workspace-layout.js");
const printExport = read("app/print-export.js");
const documentImporter = read("app/document-importer.js");
const documentStore = read("app/document-store.js");
const projectPackage = read("app/project-package.js");
const catalogSource = read("app/catalog-source.js");
const manualEntry = read("app/manual-entry.js");
const presentations = read("app/presentation-registry.js");
const sectionRecipes = read("app/section-recipes.js");

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

assert(html.includes('value="fit"'), "A barra superior não oferece o modo Ajustar.");
assert(html.includes('data-toggle-panel="left"') && html.includes('data-toggle-panel="right"'), "Os dois painéis precisam de controles de recolhimento.");
assert(editorCss.includes('max-width: 1380px') && editorCss.includes('max-height: 800px'), "O breakpoint de notebook não foi formalizado.");
assert(editorCss.includes('data-left-panel-collapsed="true"') && editorCss.includes('data-right-panel-collapsed="true"'), "O grid não reage ao estado dos painéis.");
assert(renderer.includes("--component-vector") && componentCss.includes("--component-vector"), "O token vetorial não percorre renderer e CSS.");
assert(interactions.includes("CatalogWorkspace?.getScale()"), "As interações não usam a escala efetiva do workspace.");
assert(html.includes('id="assetLibraryDialog"') && html.includes('id="assetFileInput"'), "A biblioteca de artes e o upload não estão expostos na interface.");
assert(html.indexOf('id="assetLibraryGrid"') < html.indexOf('id="assetDropzone"'), "A lista do projeto deve aparecer antes da importação do computador.");
assert(html.includes('app/asset-storage.js') && html.includes('app/asset-library.js'), "Os módulos de assets não foram carregados.");
assert(assetStorage.includes("indexedDB") && assetLibrary.includes("image/svg+xml") && assetLibrary.includes("image/webp"), "O contrato de armazenamento e formatos de arte está incompleto.");
assert(componentCss.includes("vector-token"), "A recoloração de SVG por token não está conectada ao preview.");
assert(renderer.includes("getTableRows") || read("app/component-registry.js").includes("getTableRows"), "O renderer não consulta as linhas ligadas à coleção.");
assert(inspector.includes("data-table-row-add") && inspector.includes("data-duplicate-series"), "Os controles de conteúdo repetível e duplicação avançada não estão expostos.");
assert(componentCss.includes("component-art__caption"), "A legenda vinculada à arte não possui apresentação visual.");
assert(html.includes("data-left-panel-tab") && inspector.includes("data-inspector-tab"), "A hierarquia por abas não está disponível nos dois painéis.");
assert(workspaceLayout.includes('addEventListener("wheel"') && workspaceLayout.includes("preventDefault"), "O zoom lógico por Ctrl/Cmd+roda não foi implementado.");
assert(editorCss.includes("select option") && editorCss.includes("background-color: #fff"), "O contraste explícito das opções de zoom não foi formalizado.");
assert(renderer.includes("data-within-selected-container") && renderer.includes("data-within-selection"), "A subárvore do contêiner selecionado não recebe ênfase contextual.");
assert(read("app/component-registry.js").includes('"footer-item"') && read("app/component-registry.js").includes("headerSlots"), "Cabeçalho e rodapé ainda não expõem peças editáveis.");
assert(html.includes('id="printButton"') && html.includes('app/print-export.js'), "A ação de impressão/PDF não está exposta na barra superior.");
assert(printExport.includes("window.print()") && printExport.includes("beforeprint") && printExport.includes("afterprint"), "A impressão A4 não prepara nem restaura o estado de visualização.");
assert(componentCss.includes("@page { size: A4 portrait; margin: 0; }") && componentCss.includes("background-image: none !important"), "A folha impressa não está isolada como A4 sem grid.");
assert(inspector.includes("data-slot-span") && read("app/document-store.js").includes("updateSlotSpan"), "O inspetor não controla a ocupação ponderada de slots.");
assert(read("schemas/catalog-document.schema.json").includes('"span": { "type": "integer"'), "O schema não formaliza slot.span.");
assert(inspector.includes("data-reintegrate-layout") && inspector.includes("Gerenciado pelo layout") && read("app/document-store.js").includes("setComponentLayoutAuthority"), "A autoridade local de layout não está conectada ao store e ao inspetor.");
assert(interactions.includes("selectComponentInContext"), "A árvore de camadas não realiza seleção com transição de contexto.");
assert(interactions.includes("dropContextAtEvent") && interactions.includes("event.shiftKey") && read("app/document-store.js").includes("getContextualInsertionTarget"), "A inserção não prioriza o contêiner alvo nem oferece override por Shift.");
assert(editorCss.includes(".toast { display: none !important; }") || editorCss.includes(".side-panel__topbar, .toast"), "Mensagens transitórias ainda podem aparecer na impressão.");
assert(componentCss.includes("print-color-adjust: exact") && componentCss.includes(".6mm") && componentCss.includes(".editor-component--separator { border: 0"), "A impressão não estabiliza cor, espessura e borda dos separadores.");
assert(inspector.includes("data-restore-default-child") && read("app/document-store.js").includes("restoreDefaultChild"), "A aba Estrutura não restaura tipos internos ausentes.");
assert(inspector.includes("data-add-contextual-separator") && read("app/document-store.js").includes("addContextualSeparator"), "A linha contextual não está integrada ao inspetor e ao store.");
assert(read("app/component-registry.js").includes("footerItemSlots") && read("app/component-registry.js").includes('accepts: ["icon", "text"]'), "O item de rodapé não foi atomizado.");
assert(componentCss.includes(".editor-component--layout-container > .editor-component__content { opacity: 0 !important; }"), "A Área de composição ainda possui projeção visual no PDF.");
assert(renderer.includes("data-saved-components") && renderer.includes("data-template-id"), "A categoria Meus componentes não está separada na biblioteca.");
assert(inspector.includes("data-save-component-template") && interactions.includes("application/x-catalog-template"), "Salvar e reinserir componentes não percorre inspetor e drag and drop.");
assert(read("app/component-registry.js").includes('"art-gallery"') && read("app/component-registry.js").includes("GALERIA DE VARIAÇÕES"), "A composição multiarte não foi registrada.");
assert(componentCss.includes("component-art-gallery-shell") && componentCss.includes(".editor-component--art-gallery > .editor-component__content { opacity: 0 !important; }"), "A galeria não possui projeção própria ou limpeza no PDF.");
assert(read("app/document-store.js").includes("getCardNumberChangePlan") && inspector.includes("Continuar os próximos cards"), "A numeração assistida não está conectada ao store e à interface.");
assert(read("schemas/catalog-document.schema.json").includes('"cardNext"') && read("schemas/catalog-document.schema.json").includes('"templateItem"'), "O schema não formaliza sequência e templates.");
assert(html.includes('data-left-panel-tab="products"') && html.includes('id="productCatalogRoot"') && html.includes('app/product-catalog.js'), "O inventário não está exposto como categoria superior do painel esquerdo.");
assert(productCatalog.includes("data-product-form") && productCatalog.includes("data-subcatalog-create") && productCatalog.includes("data-product-bind"), "Cadastro, seleção, subcatálogo e vínculo não percorrem a interface de produtos.");
assert(inspector.includes("data-card-product-id") && inspector.includes("data-card-template-id") && inspector.includes("data-product-override"), "O inspetor não separa produto, apresentação e overrides locais.");
assert(read("app/document-store.js").includes("refreshBoundCards") && read("app/document-store.js").includes("applyProductTemplate"), "O store não formaliza atualização granular e template de apresentação.");
assert(read("schemas/catalog-document.schema.json").includes('"productBinding"') && read("schemas/catalog-document.schema.json").includes('"subcatalogItem"'), "O schema não formaliza binding e subcatálogos.");
assert(html.includes('id="undoButton"') && html.includes('id="redoButton"') && html.includes("Novo documento"), "Histórico e Novo documento não estão expostos na toolbar.");
assert(html.includes('id="importDocumentDialog"') && html.includes('id="documentImportFileInput"') && html.includes('app/document-importer.js'), "A importação segura de JSON não está exposta.");
assert(documentStore.includes("captureHistory") && documentStore.includes("history-undo") && documentStore.includes("getExportDocument"), "O store não separa histórico, sessão e documento autoral.");
assert(documentImporter.includes("MAX_FILE_SIZE") && documentImporter.includes("analyzeDocument") && documentImporter.includes("replaceDocument"), "O importador não analisa em memória antes do commit.");
assert(html.includes('id="exportPackageButton"') && html.includes('id="exportAuthoringKitButton"') && html.includes('vendor/fflate.js'), "Pacote portátil e kit de autoria não estão expostos na toolbar.");
assert(html.includes('id="exportPublicationPackageButton"') && projectPackage.includes('target === "publication"'), "Os gates de rascunho/publicação não estão expostos.");
assert(html.includes(".zip,application/json") && documentImporter.includes("analyzePackage") && documentImporter.includes("commitPackage"), "O diálogo não unifica JSON e pacote com commit em duas fases.");
assert(projectPackage.includes("inspectZip") && projectPackage.includes("UNSAFE_PATH") && projectPackage.includes("HASH_MISMATCH"), "O preflight não formaliza caminhos seguros e integridade SHA-256.");
assert(projectPackage.includes('assetMode: "assisted"') && projectPackage.includes("buildCapabilitiesManifest") && projectPackage.includes("commitPackage"), "Política, capacidades e remapeamento atômico estão incompletos.");
assert(html.includes("app/catalog-source.js") && catalogSource.includes("CatalogSource") && read("schemas/catalog-source.schema.json").includes('"sourceFormat"'), "CatalogSource não está formalizado no runtime e no kit.");
assert(html.includes("app/presentation-registry.js") && presentations.includes("DENSITIES") && inspector.includes("data-presentation-path"), "Preset, modo e densidade não percorrem registro e inspetor.");
assert(inspector.includes("Conteúdo") && inspector.includes("Layout") && inspector.includes("Visual") && inspector.includes("inspector-advanced") && inspector.includes("data-toggle-all-properties"), "O inspetor não aplica a hierarquia progressiva por tarefa.");
assert(inspector.includes("data-table-column-add") && inspector.includes("data-table-cell-legend") && documentStore.includes("setTableCellLegend"), "Tabela genérica e legenda semântica não percorrem a interface.");
assert(documentStore.includes("getMinimumProfile") && inspector.includes("data-custom-minimum-enabled"), "Mínimos técnico e recomendado não foram separados.");
assert(read("authoring-kit/GUIDE.md").includes("CatalogProjectPackage") && read("authoring-kit/manifest.json").includes("CatalogAuthoringKit"), "A primeira versão do kit de autoria não está disponível.");
assert(interactions.includes('event.key.toLowerCase() === "z"') && interactions.includes("this.store.redo()"), "Os atalhos de desfazer/refazer não estão conectados.");
assert(html.includes("app/manual-entry.js") && productCatalog.includes("data-products-bulk-add") && productCatalog.includes("data-products-create-cards"), "A entrada rápida e a criação manual de cards em lote não percorrem a interface.");
assert(inspector.includes("data-table-bulk-apply") && documentStore.includes("replaceTableRowsBulk") && documentStore.includes("runCompoundChange"), "A colagem de tabela e as transações manuais compostas não percorrem inspetor e store.");
assert(inspector.includes("data-gallery-bulk-apply") && documentStore.includes("applyGalleryItemsBulk") && manualEntry.includes("parseGallery"), "A edição em lote da galeria não percorre parser, inspetor e store.");
assert(inspector.includes("data-legend-bulk-apply") && documentStore.includes("upsertColorLegendsBulk") && manualEntry.includes("parseLegends"), "A edição em lote de legendas não percorre parser, inspetor e store.");
assert(inspector.includes("batch-geometry-status") && documentStore.includes("getSelectionGeometryReport"), "O diagnóstico geométrico contextual não está exposto para a seleção.");
assert(inspector.includes("data-batch-frames-apply") && documentStore.includes("applyComponentFramesBulk") && manualEntry.includes("parseFrames"), "A grade heterogênea de caixas não percorre parser, inspetor e store.");
assert(manualEntry.includes("parseProducts") && manualEntry.includes("parseTable") && manualEntry.includes("parseDelimited"), "O parser tabular manual não cobre produtos e tabelas.");
assert(html.includes("app/section-recipes.js") && sectionRecipes.includes("page-catalog-base") && sectionRecipes.includes("primary-content"), "O registro oficial de receitas ou seu foco não está carregado.");
assert(renderer.includes("data-insert-template") && renderer.includes("data-insert-component") && interactions.includes("insertComponentFromTemplate"), "A inserção contextual por um clique não percorre biblioteca e store.");
assert(projectPackage.includes("officialSectionRecipes") && read("schemas/catalog-capabilities.schema.json").includes('"recipes"'), "Receitas oficiais não estão declaradas no manifesto de capacidades.");
assert(renderer.includes("data-context-action") && interactions.includes("performContextualAction") && documentStore.includes("addArtVariation"), "O + contextual não percorre interface e store.");
assert(inspector.includes("data-batch-spacing-apply") && documentStore.includes("spaceComponents") && documentStore.includes("addSeparatorsForComponents"), "Espaçamento e separadores em lote não percorrem inspetor e store.");
assert(inspector.includes("data-batch-equalize") && inspector.includes("data-batch-frame-apply") && inspector.includes("data-batch-delta-apply") && documentStore.includes("transformComponents"), "A geometria integrada da multisseleção não percorre inspetor e store.");
assert(inspector.includes("taskStateByType") && inspector.includes("rememberTaskState") && inspector.includes("restoreTaskState"), "O inspetor não preserva a tarefa entre componentes equivalentes.");
assert(interactions.includes("requireActionResult") && interactions.includes("não pode ser inserido no contexto atual"), "Ações sem resultado ainda podem falhar silenciosamente.");
assert(read("app/component-registry.js").includes("CATALOG_SEPARATOR_PRESETS") && projectPackage.includes("separatorPresets"), "Presets editáveis de separador não foram declarados.");
const schema = JSON.parse(read("schemas/catalog-document.schema.json"));
assert(schema.properties.schemaVersion.const === "1.16.0" && !schema.required.includes("editor"), "O schema 1.16 não preservou a sessão de editor opcional.");
assert(html.includes('id="visualizationMenu"') && editorCss.includes("toolbar-visualization__controls"), "O agrupamento responsivo de Visualização não foi publicado.");
assert(read("authoring-kit/manifest.json").includes('"featureInventory": "feature-inventory.json"') && read("docs/FEATURE-CATALOG.md").includes("Fluxos por intenção"), "O atlas funcional do 05.11 não está disponível.");

console.log("✓ Contratos estáticos, chrome responsivo e atlas funcional 05.11 validados.");
